mod 'puppetlabs-stdlib', '8.4.0'
mod 'puppetlabs-concat', '7.2.0'
mod 'puppet-archive', '6.0.2'
mod 'puppetlabs-java', '8.2.0'
mod 'puppet-nginx', '4.0.0'
mod 'puppetlabs-apache', '8.1.0'
mod 'puppetlabs-inifile', '5.3.0'
mod 'puppet-php', '8.1.0'